### PR TITLE
LocalCopy

### PR DESCRIPTION
**Pull request by cra0zy**

### CODE REVIEW

**Comment by hach-que** [comment]
@cra0zy I will need you in the near future to sign this: https://cla.dotnetfoundation.org/ (you can't yet though because the project acceptance isn't finalised).  Are you okay with this?

**Comment by cra0zy** [comment]
> @cra0zy I will need you in the near future to sign this: https://cla.dotnetfoundation.org/ (you can't yet though because the project acceptance isn't finalised). Are you okay with this?

No problem. Just tell me when you need it signed.

**Comment by hach-que** [comment]
This is now merged as ffb4d5d.

**Comment by hach-que** [comment]
I'll be sending around emails to all contributors of this repository once I hear back from the .NET Foundation as to what documents need signing.

**Pull request closed without merging**
